server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/imooc_coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qing
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000
  kafka:
    bootstrap-servers:   # broker 列表，数组结构
      - 127.0.0.1:9092
    consumer:
      group-id: imooc-distribution-x  # 消费者默认的 group id
      auto-offset-reset: latest    # 消费者默认的消费策略，这里指的是从最新的位置开始消费，即不管之前的消息
  # 开启 ribbon 重试机制, 即获取服务失败是否从另外一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

logging:
  level:
    com.imooc.distribution: debug

# feign 相关的配置
feign:
  hystrix:
    enabled: true   # Hystrix 默认是关闭的
  client:
    config:
      default:  # 全局的
        connectTimeout: 2000  # 默认的连接超时时间是 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # 单独服务的配置
        connectTimeout: 3000  # 默认的连接超时时间是 10s
        readTimeout: 5000